### ISSUE TITLE
Ex 1-23: Division operator gets wrongly matched as an inline comment

### ISSUE THREAD

**Issue by ajizanci** [ohkimur/the-c-programming-language-2nd-edition-solutions#30]
**Describe the bug**
Expressions like "2 / 3" get treated as inline comments, so "/ 3" is removed from the final string leaving only "2".

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the program with any input featuring a single forward slash e.g. a simple expression like the one above. 
2. The output generated is not the desired one, having any division operation removed.

**Expected behaviour**
Everything after a single forward slash should not be considered a comment.

**Possible fix**
The conditional on line 77 is only really checking for one thing as the second part of the AND expression is exactly the same as the first.
```c
      if (str[i] == '/' && str[i] == '/')
```
The second part should be ``str[i + 1] == '/'`` instead.

**Comment by ohkimur** [comment]
@ajizanci Thanks for the observation. Can you make a PR to fix this?

**Comment by ajizanci** [comment]
Sure! Let me get to it.
