### ISSUE TITLE
strindex of exercise_5_06 always return -1, if the char t[] is modified to "this"

### ISSUE THREAD

**Issue by metalbuild-mnbv** [ohkimur/the-c-programming-language-2nd-edition-solutions#33]
**Describe the bug**
I changed the definition  of char t[] = "first" to char t[] = "this", this should make the return value to 0, which is the first element of char s[].
However the  return value is -1, since the _while_ statement and the first _if_ statement are not consistent.
After _while_ (*s++ != '\0'), the first  _if_ statement must skip the first element of s[], which is the character t of "this".
Meanwhile, the increment of variable _pos_ is premature. It cannot show the index 0 correctly also if the t[] appears at the first position of s[] as the same reason above.

**To Reproduce**
1. Modify char t[] = "first" to char t[] = "this".
2. Recompile this program.
3. Result on terminal should be -1.

**Expected behavior**
t[] = "this" should be matched char s[]  = "this is first string" and the return value is 0.

**Additional context**
Workaround is provided below.

```
while (*s != '\0')                   /* removed ++ for consistency with the next if */
  {                                 /* ++pos deleted and moved to new position in which after the completion of if
                                                                      (*s == *t) */
    if (*s == *t)
    {
      first = s;
      second = t;

      while (*first++ == *second++)
      {
        if (*second == '\0')
          return pos;
      }
    }
    pos++;                                 /* new position of pos increment */
    s++;                                      /* increment of s for next loop */
  }
```

**Comment by ohkimur** [comment]
@metalbuild-mnbv Can you make a pull requrest?
