### ISSUE TITLE
1.20: solution is not correct

### ISSUE THREAD

**Issue by unsubtract** [ohkimur/the-c-programming-language-2nd-edition-solutions#43]
The exercise states that the program should replace input tabs with the proper number of spaces to reach the next tab stop. The tab stops are at fixed intervals (like every 4 columns or every 8) and the spaces should only fill up until the next stop, mimicking the behavior of actual tabs.

For example, given the input 'as[\t]df' where [\t] is a tab character, it should return 'as&ensp;&ensp;df' with a tab stop of 4 (inserting two spaces, as there are already two characters) or 'as&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;df' with a tab stop of 8 (inserting six spaces), etc.

As currently implemented, this is not the case and the tab is simply substituted for 8 spaces.

**Comment by ohkimur** [comment]
@unsubtract If you like to can take the time to adapt the current solution and make a PR.

**Comment by ohkimur** [comment]
@unsubtract I'll close this issue due to inactivity. If you still want to improve it, just make a PR. I'll gladly merge it as long as it is consistent with the repo.

**Comment by berkenvr** [comment]
Can you reopen this issue? I want to help. @ohkimur
