### ISSUE TITLE
wrong result for 'escape sequence chain' - Exercise 1-12.

### ISSUE THREAD

**Issue by caldotdev** [ohkimur/the-c-programming-language-2nd-edition-solutions#58]
https://github.com/ohkimur/the-c-programming-language-2nd-edition-solutions/blob/1506a2a6fb59d663aa36c382873a9c3d0f486089/chapter_1/exercise_1_12/copy_io_nl.c#L1-L22

Imagine the input being ` \t`

1. `c = ' '`
2. `last_char = ' '` and `c = '\t'` here `c != last_char` evaluates to true and a newline would be printed to stdout although no new word started

e.g.
```
This \tTest
```

I think having additional checks would fix this. I just recently started learning C so I am potentially missing something here..

```c
#include <stdio.h>

int main() {
  int c, prev;
  prev = EOF;

  while ((c = getchar()) != EOF) {
    if (c == ' ' || c == '\t' || c == '\n') {
      if (prev != ' ' && prev != '\t' && prev != '\n') {
        putchar('\n');
      }
    } else {
      putchar(c);
    }

    prev = c;
  }

  return 0;
}
```

**Comment by ohkimur** [comment]
@caldotdev Thanks for spotting this up. Can you make pull request to implement your solution? Please preserve the formatting.

**Comment by caldotdev** [comment]
Will do so by then end of this week 👍🏻

**Comment by caldotdev** [comment]
Haven't forgot about it - just got smashed with work!
